// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Echo implements echo operation.
//
// POST /echo
func (UnimplementedHandler) Echo(ctx context.Context, req OptString) (r *StringMessage, _ error) {
	return r, ht.ErrNotImplemented
}

// PathParam implements pathParam operation.
//
// POST /pathParam/{value}
func (UnimplementedHandler) PathParam(ctx context.Context, params PathParamParams) (r *StringMessage, _ error) {
	return r, ht.ErrNotImplemented
}

// TestModelEndpoint implements testModelEndpoint operation.
//
// POST /testModel
func (UnimplementedHandler) TestModelEndpoint(ctx context.Context, req *TestModel) (r *TestModel, _ error) {
	return r, ht.ErrNotImplemented
}
