// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s TestEnum) Validate() error {
	switch s {
	case "DEVICE_UNKNOWN":
		return nil
	case "DEVICE_KEYBOARD":
		return nil
	case "DEVICE_MOUSE":
		return nil
	case "DEVICE_MONITOR":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
func (s *TestModel) Validate() error {
	var failures []validate.FieldError
	if err := func() error {
		if s.OptionalFloat.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.OptionalFloat.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "optionalFloat",
			Error: err,
		})
	}
	if err := func() error {
		if s.OptionalDouble.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.OptionalDouble.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "optionalDouble",
			Error: err,
		})
	}
	if err := func() error {
		if s.RecursiveChild == nil {
			return nil // optional
		}
		if err := func() error {
			if err := s.RecursiveChild.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			return errors.Wrap(err, "pointer")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "recursiveChild",
			Error: err,
		})
	}
	if err := func() error {
		if s.Category.Set {
			if err := func() error {
				if err := s.Category.Value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "category",
			Error: err,
		})
	}
	if err := func() error {
		if s.Double.Set {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(s.Double.Value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "double",
			Error: err,
		})
	}
	if err := func() error {
		if s.ImportedEnum.Set {
			if err := func() error {
				if err := s.ImportedEnum.Value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "importedEnum",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
func (s TestModelCategory) Validate() error {
	switch s {
	case "UNKNOWN":
		return nil
	case "IMAGES":
		return nil
	case "NEWS":
		return nil
	case "VIDEO":
		return nil
	case "RADIO":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
