openapi: 3.1.0
info:
  title: ""
  version: ""
paths:
  /api/v1/items/{id}:
    get:
      operationId: getItem
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: crud.v1.Crud.GetItem response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        ipv4:
          type: string
          format: ipv4
        ipv6:
          type: string
          format: ipv6
        ip:
          type: string
          format: ip
      required:
        - id
        - ipv4
        - ipv6
        - ip
