openapi: 3.1.0
info:
    title: ""
    version: ""
paths:
    /api/v1/{id}:
        put:
            operationId: putMethod
            parameters:
                -   $ref: '#/components/parameters/Id'
            requestBody:
                $ref: '#/components/requestBodies/Request'
            responses:
                "200":
                    $ref: '#/components/responses/Response'
components:
    responses:
        Response:
            description: Response
            content:
                application/json:
                    schema:
                        type: object
    parameters:
        Id:
            name: id
            in: path
            required: true
            schema:
                type: string
    requestBodies:
        Request:
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            body:
                                type: string
