openapi: 3.0.0
info:
    title: ""
    version: ""
paths:
    /api/v1/{id}:
        get:
            operationId: getMethod
            parameters:
                -   $ref: '#/components/parameters/Id'
                -   $ref: '#/components/parameters/Query'
            responses:
                "200":
                    $ref: '#/components/responses/Response'
components:
    responses:
        Response:
            description: Response
            content:
                application/json:
                    schema:
                        type: object
    parameters:
        Id:
            name: id
            in: path
            required: true
            schema:
                type: string
        Query:
            name: query
            in: query
            required: true
            schema:
                type: string
